// Generates docs/PERFORMANCE.md (and the README summary block) from eval/results/history.jsonl.
// Usage: npm run report
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const hist = fs.readFileSync(path.join(root, 'eval/results/history.jsonl'), 'utf8').trim().split('\n').filter(Boolean).map((l) => JSON.parse(l));
if (!hist.length) { console.error('No history yet — run `npm run eval` first.'); process.exit(1); }

const f = (n, d = 2) => (n == null ? '—' : Number(n).toFixed(d));
const sec = (ms) => (ms == null ? '—' : (ms / 1000).toFixed(1) + 's');
const pct = (n) => (n == null ? '—' : Math.round(n * 100) + '%');
const day = (d) => d.slice(0, 16).replace('T', ' ') + ' UTC';
const last = hist.at(-1);
const withPerf = [...hist].reverse().find((h) => h.latencyP50 != null);

const status = (h) => {
  const checks = [h.mae <= 0.8, Math.abs(h.bias) <= 0.3, h.within1 >= 0.85, h.adv && h.adv[0] === h.adv[1]];
  return checks.every(Boolean) ? '✅' : '⚠️';
};

const summary = `| Metric | Latest | Target |
|---|---|---|
| Calibration MAE vs human labels | **${f(last.mae)}** | ≤ 0.80 |
| Bias (+ = AI too generous) | **${last.bias >= 0 ? '+' : ''}${f(last.bias)}** | within ±0.30 |
| Scores within ±1 of human | **${pct(last.within1)}** | ≥ 85% |
| Ranking agreement | **${last.rank ? last.rank[0] + '/' + last.rank[1] : '—'}** | 100% |
| Failure-mode tests passed | **${last.adv ? last.adv[0] + '/' + last.adv[1] : '—'}** | 100% |
| Latency per answer (p50 / p95) | **${withPerf ? sec(withPerf.latencyP50) + ' / ' + sec(withPerf.latencyP95) : 'not yet measured'}** | < 15s p50 |
| Tokens per answer | **${withPerf ? withPerf.avgTokens : '—'}** | — |

<sub>Latest run: ${day(last.date)} · set \`${last.set || 'pm-v1'}\` · \`${last.model}\` · ${last.cases} cases × ${last.runsPerCase} run(s) · ${last.source}</sub>`;

const rows = [...hist].reverse().slice(0, 25).map((h, i) =>
  `| ${day(h.date)} | ${h.set || 'pm-v1'} | \`${h.model}\` | ${h.runsPerCase} | ${f(h.mae)} | ${h.bias >= 0 ? '+' : ''}${f(h.bias)} | ${pct(h.within1)} | ${h.rank ? h.rank.join('/') : '—'} | ${h.adv ? h.adv.join('/') : '—'} | ${sec(h.latencyP50)} | ${sec(h.latencyP95)} | ${h.avgTokens ?? '—'} | ${status(h)} | ${h.note || h.source || ''} |`).join('\n');

const xs = hist.map((_, i) => `"#${i + 1}"`).join(', ');
const charts = `\`\`\`mermaid
xychart-beta
    title "Calibration error (MAE) per eval run — lower is better"
    x-axis [${xs}]
    y-axis "MAE" 0 --> 1
    line [${hist.map((h) => f(h.mae)).join(', ')}]
\`\`\`

\`\`\`mermaid
xychart-beta
    title "Failure-mode tests passed per eval run"
    x-axis [${xs}]
    y-axis "passed" 0 --> ${Math.max(...hist.map((h) => h.adv?.[1] || 0), 1)}
    bar [${hist.map((h) => h.adv?.[0] ?? 0).join(', ')}]
\`\`\``;

const flagTotals = {};
hist.forEach((h) => Object.entries(h.flags || {}).forEach(([k, v]) => (flagTotals[k] = (flagTotals[k] || 0) + v)));
const lastFlags = last.flags ? Object.entries(last.flags).map(([k, v]) => `- \`${k}\`: ${v}`).join('\n') : '_not recorded for this run_';

const doc = `# Performance

> Auto-generated by \`npm run report\` from [\`eval/results/history.jsonl\`](../eval/results/history.jsonl). Do not edit by hand.
> Usage and user-feedback stats live in [USAGE.md](USAGE.md).

## Latest

${summary}

## Trend

${charts}

## Run history

| Date | Set | Model | Runs/case | MAE | Bias | ±1 | Rank | Fail-mode | p50 | p95 | Tokens | Status | Note |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
${rows}

✅ = meets all targets (MAE ≤ 0.8, |bias| ≤ 0.3, ≥85% within ±1, all failure-mode tests pass).

## Guardrail activity (latest run)

${lastFlags}

High counts of \`rewrite_repaired\` or \`dropped_unverified_quote\` mean the underlying model often makes unsupported claims and the guardrails are doing real work — see [failure-modes.md](failure-modes.md).

## How these numbers are produced

- **Calibration** — 8 human-labelled answers; the AI's per-criterion scores are compared to the labels (single rater — see caveat in [evaluation-framework.md](evaluation-framework.md)).
- **Failure modes** — 7 adversarial cases with machine-checkable expectations.
- **Latency / tokens** — wall time and token usage across all model calls for one answer (evaluate + rewrite audit), measured in \`lib/llm.js\`.
- Runs: \`npm run eval\` locally, or the **Eval** GitHub Actions workflow (manual + weekly), which also publishes this summary to the run page.
`;
fs.writeFileSync(path.join(root, 'docs/PERFORMANCE.md'), doc);

// README block
const readmePath = path.join(root, 'README.md');
let readme = fs.readFileSync(readmePath, 'utf8');
const block = `<!-- perf:start -->\n### Latest evaluation ${status(last)}\n\n${summary}\n\n[Full history & trend →](docs/PERFORMANCE.md) · [Usage & user feedback →](docs/USAGE.md)\n<!-- perf:end -->`;
readme = readme.includes('<!-- perf:start -->')
  ? readme.replace(/<!-- perf:start -->[\s\S]*<!-- perf:end -->/, block)
  : readme.replace('## Getting started', `${block}\n\n## Getting started`);
fs.writeFileSync(readmePath, readme);
console.log('Wrote docs/PERFORMANCE.md and README summary');
