// Aggregates app usage into docs/USAGE.md — counts and rates only, never answer text or resumes.
// Usage: npm run usage                       (reads data/*.jsonl written by the local server)
//        node scripts/usage.js logs.txt      (e.g. from `vercel logs --no-follow --limit 1000 > logs.txt`;
//                                              picks up lines like  [turns.jsonl] {...}  — best effort)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (file) => (fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '');
const jsonl = (txt) => txt.split('\n').map((l) => { try { return JSON.parse(l); } catch { return null; } }).filter(Boolean);

let turns, feedback, sessions;
const arg = process.argv[2];
if (arg) {
  const grab = (tag) => read(arg).split('\n').flatMap((l) => { const i = l.indexOf(`[${tag}] {`); if (i < 0) return []; try { return [JSON.parse(l.slice(i + tag.length + 3))]; } catch { return []; } });
  [turns, feedback, sessions] = [grab('turns.jsonl'), grab('feedback.jsonl'), grab('sessions.jsonl')];
} else {
  [turns, feedback, sessions] = ['turns', 'feedback', 'sessions'].map((n) => jsonl(read(path.join(root, `data/${n}.jsonl`))));
}

const mean = (a) => (a.length ? a.reduce((x, y) => x + y, 0) / a.length : null);
const q = (a, p) => { const v = [...a].sort((x, y) => x - y); return v.length ? v[Math.min(v.length - 1, Math.floor(p * v.length))] : null; };
const f = (n, d = 1) => (n == null ? '—' : Number(n).toFixed(d));
const pct = (n, d) => (d ? Math.round((100 * n) / d) + '%' : '—');

let body;
if (!turns.length && !feedback.length && !sessions.length) {
  body = '_No usage data yet. Run the app, answer a few questions, then run `npm run usage`._';
} else {
  const uniq = new Set(turns.map((t) => t.sessionId).filter(Boolean));
  const main = turns.filter((t) => !t.isFollowUp);
  const voice = turns.filter((t) => t.inputMode === 'voice').length;
  const overalls = turns.map((t) => t.evaluation?.overall).filter(Number.isFinite);
  const lat = turns.map((t) => t.meta?.latencyMs).filter(Number.isFinite);
  const tok = turns.map((t) => t.meta?.totalTokens).filter(Number.isFinite);
  const words = turns.map((t) => (t.answer || '').trim().split(/\s+/).filter(Boolean).length);
  const conf = { high: 0, medium: 0, low: 0 }; turns.forEach((t) => { const c = t.evaluation?.confidence; if (c in conf) conf[c]++; });
  const flagCount = {}; turns.forEach((t) => (t.flags || []).forEach((x) => (flagCount[x.type] = (flagCount[x.type] || 0) + 1)));
  const withFlags = turns.filter((t) => (t.flags || []).length).length;
  const dist = [1, 2, 3, 4, 5].map((b) => overalls.filter((o) => Math.round(o) === b).length);
  const rate = { accurate: 0, partly: 0, wrong: 0 }; feedback.forEach((x) => { if (x.rating in rate) rate[x.rating]++; });
  const rated = rate.accurate + rate.partly + rate.wrong;
  const roles = {}; turns.forEach((t) => { if (t.role) roles[t.role] = (roles[t.role] || 0) + 1; });

  body = `## Volume
| Metric | Value |
|---|---|
| Interviews started | ${sessions.filter((s) => s.event === 'start').length || '—'} |
| Sessions with ≥1 answer | ${uniq.size} |
| Answers evaluated | ${turns.length} (${main.length} main + ${turns.length - main.length} follow-up) |
| Follow-up answer rate | ${pct(turns.length - main.length, main.length)} of main answers |
| Voice-mode answers | ${pct(voice, turns.length)} |
| Median answer length | ${q(words, 0.5) ?? '—'} words |

## Performance in the field
| Metric | Value |
|---|---|
| Latency per answer p50 / p95 | ${lat.length ? `${f(q(lat, 0.5) / 1000)}s / ${f(q(lat, 0.95) / 1000)}s` : '—'} |
| Tokens per answer (avg) | ${tok.length ? Math.round(mean(tok)) : '—'} |

## Score distribution (overall, rounded)
| 1 | 2 | 3 | 4 | 5 | Mean |
|---|---|---|---|---|---|
| ${dist.join(' | ')} | ${f(mean(overalls))} |

## Reliability
| Metric | Value |
|---|---|
| Coach confidence high / medium / low | ${conf.high} / ${conf.medium} / ${conf.low} |
| Answers with ≥1 guardrail flag | ${pct(withFlags, turns.length)} |
${Object.entries(flagCount).sort((a, b) => b[1] - a[1]).map(([k, v]) => `| \`${k}\` | ${v} |`).join('\n')}

## User-rated feedback accuracy
${rated ? `| 👍 Accurate | 🤔 Partly | 👎 Misleading | Rated |
|---|---|---|---|
| ${pct(rate.accurate, rated)} (${rate.accurate}) | ${pct(rate.partly, rated)} (${rate.partly}) | ${pct(rate.wrong, rated)} (${rate.wrong}) | ${rated} of ${turns.length} answers |

Target: ≥70% accurate/partly, <10% misleading.` : '_No ratings yet._'}

## Roles practised
${Object.entries(roles).sort((a, b) => b[1] - a[1]).slice(0, 10).map(([k, v]) => `- ${k}: ${v}`).join('\n') || '_none_'}`;
}

fs.writeFileSync(path.join(root, 'docs/USAGE.md'), `# Usage & user feedback

> Auto-generated by \`npm run usage\` (${new Date().toISOString().slice(0, 10)}). Aggregates only — no resumes or answers are published.
> Source: ${arg ? `\`${path.basename(arg)}\`` : 'local `data/*.jsonl`'}. Eval/performance trends are in [PERFORMANCE.md](PERFORMANCE.md).

${body}
`);
console.log('Wrote docs/USAGE.md');
